import cv2 as cv
from criteria import SNR,PSNR,MSE,SSIM
from mynoise import NoiseForImage
img= NoiseForImage("./img/brain.jpg")
img_natural = NoiseForImage("./img/brain.jpg")
img_natural.grayscale_image()
img.grayscale_image()
img.gaussian_noise(0,0.05)
# img.speckle_noise()
img_natural.show()
img.show("Noise image")
value_img = img.get_image_matrix()
value_natural_img = img_natural.get_image_matrix()
mse_value = MSE(value_natural_img, value_img)
psnr_value = PSNR(value_natural_img, value_img)
SNR_value = SNR(value_natural_img, value_img)
SSIM_value = SSIM(value_natural_img, value_img)
print("MSE :",mse_value)
print("PSNR :",psnr_value)
print("SNR :",SNR_value)
print(value_img)
cv.waitKey(0)
